app/urls.py
__author__ = 'parentj@eab.com (Jason Parent)'

# Django imports...
from django.conf.urls import patterns, url

urlpatterns = patterns('app.views',
    url(r'^$', 'home_view', name='home'),
    url(r'^event/$', 'event_view', name='event'),
    url(r'^event/new/$', 'new_event_view', name='new_event'),
    url(r'^event/(?P<event_id>\d+)/$', 'event_detail_view', name='event_detail'),
    url(r'^event/list/$', 'event_list_view', name='event_list'),
)

bottlebattle/urls.py
__author__ = 'parentj@eab.com (Jason Parent)'

# Django imports...
from django.conf import settings
from django.conf.urls import include, patterns, url
from django.conf.urls.static import static
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'accounts.views.home_view', name='home'),
    url(r'^sign_up/$', 'accounts.views.sign_up_view', name='sign_up'),
    url(r'^log_in/$', 'accounts.views.log_in_view', name='log_in'),
    url(r'^log_out/$', 'accounts.views.log_out_view', name='log_out'),
    url(r'^profile/$', 'accounts.views.profile_view', name='profile'),
    url(r'^profile/edit/$', 'accounts.views.profile_edit_view', name='profile_edit'),
    # url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^app/', include('app.urls', namespace='app')),
    # url(r'^', include('web.urls', namespace='web')),
    url(r'^admin/', include(admin.site.urls)),
)

# Serves media files in development environment...
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/templates/web/home.html
{% extends 'base.html' %}

{% block page-styles %}{% endblock page-styles %}

{% block page-navigation %}
    {% include 'snippets/navigation.html' with active='none' %}
{% endblock page-navigation %}

{% block page-content %}
    <div id="wrapper">
        <h1>Welcome to Bottle Battle</h1>
        {% if user.is_authenticated %}
            <a id="feed_button" class="btn btn-large btn-primary" href="{% url 'app:home' %}">Continue to App</a>
        {% else %}
            <a id="log_in_button" class="btn btn-large btn-primary" href="{% url 'log_in' %}">Log in</a>
            <a id="sign_up_button" class="btn btn-large btn-primary" href="{% url 'sign_up' %}">Sign up</a>
        {% endif %}
    </div>
{% endblock page-content %}