app/urls.py
__author__ = 'parentj@eab.com (Jason Parent)'

# Django imports...
from django.conf.urls import patterns, url

urlpatterns = patterns('app.views',
    url(r'^$', 'home_view', name='home'),
    url(r'^event/$', 'event_view', name='event'),
    url(r'^event/new/$', 'new_event_view', name='new_event'),
    url(r'^event/(?P<event_id>\d+)/$', 'event_detail_view', name='event_detail'),
    url(r'^event/list/$', 'event_list_view', name='event_list'),
)

bottlebattle/urls.py
__author__ = 'parentj@eab.com (Jason Parent)'

# Django imports...
from django.conf import settings
from django.conf.urls import include, patterns, url
from django.conf.urls.static import static
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'accounts.views.home_view', name='home'),
    url(r'^sign_up/$', 'accounts.views.sign_up_view', name='sign_up'),
    url(r'^log_in/$', 'accounts.views.log_in_view', name='log_in'),
    url(r'^log_out/$', 'accounts.views.log_out_view', name='log_out'),
    url(r'^profile/$', 'accounts.views.profile_view', name='profile'),
    url(r'^profile/edit/$', 'accounts.views.profile_edit_view', name='profile_edit'),
    # url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^app/', include('app.urls', namespace='app')),
    # url(r'^', include('web.urls', namespace='web')),
    url(r'^admin/', include(admin.site.urls)),
)

# Serves media files in development environment...
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/templates/app/event.html
{% extends 'base.html' %}

{% block page-styles %}{% endblock page-styles %}

{% block page-navigation %}
    {% include 'snippets/navigation.html' with active='none' %}
{% endblock page-navigation %}

{% block page-content %}

{% endblock page-content %}

app/templates/app/event_detail.html
{% extends 'base.html' %}

{% block page-styles %}{% endblock page-styles %}

{% block page-navigation %}
    {% include 'snippets/navigation.html' with active='none' %}
{% endblock page-navigation %}

{% block page-content %}

{% endblock page-content %}

app/templates/app/event_list.html
{% extends 'base.html' %}

{% block page-styles %}{% endblock page-styles %}

{% block page-navigation %}
    {% include 'snippets/navigation.html' with active='none' %}
{% endblock page-navigation %}

{% block page-content %}

{% endblock page-content %}

app/templates/app/home.html
{% extends 'base.html' %}

{% block page-styles %}{% endblock page-styles %}

{% block page-navigation %}
    {% include 'snippets/navigation.html' with active='none' %}
{% endblock page-navigation %}

{% block page-content %}
    <div class="center-middle">
        <h1>Bottle Battle</h1>
        <a id="host_button" class="btn btn-large btn-primary" href="{% url 'app:new_event' %}">Host event</a>
        <a id="join_button" class="btn btn-large btn-primary" href="{% url 'app:event' %}">Join event</a>
    </div>
{% endblock page-content %}

app/templates/app/new_event.html
{% extends 'base.html' %}

{% block page-styles %}{% endblock page-styles %}

{% block page-navigation %}
    {% include 'snippets/navigation.html' with active='none' %}
{% endblock page-navigation %}

{% block page-content %}
    <div class="row">
        <div class="col-sm-offset-3 col-sm-6 col-md-offset-4 col-md-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4 class="panel-title">New Event</h4>
                </div>
                <div class="panel-body">
                    {% include 'bootstrap_messages.html' %}
                    {% for error in form.non_field_errors %}
                        <div class="alert alert-danger alert-dismissable">
                            <button class="close" type="button" data-dismiss="alert">&times;</button>
                            {{ error|safe }}
                        </div>
                    {% endfor %}
                    <form action="{% url 'log_in' %}" method="post">
                        {% csrf_token %}
                        {% for field in form %}
                            {% if field.errors %}
                                <div class="form-group has-error has-feedback">
                                    {{ field.label_tag }}
                                    {{ field }}
                                    <span class="help-block">
                                        {{ field.errors|join:', ' }}
                                    </span>
                                </div>
                            {% else %}
                                <div class="form-group">
                                    {{ field.label_tag }}
                                    {{ field }}
                                </div>
                            {% endif %}
                        {% endfor %}
                        <button id="create_button" class="btn btn-primary" type="submit">Create</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock page-content %}